security:
  funcs:
    getenv: ["^HUGO_", "^CI$", "WC_POST_CSS"]

title: "성윤오 | 전북대 컴퓨터인공지능학부 학생"
baseURL: "https://s44158619-code.github.io/"

defaultContentLanguage: ko
hasCJKLanguage: true
defaultContentLanguageInSubdir: true
removePathAccents: true

enableGitInfo: false
summaryLength: 30
paginate: 10
enableEmoji: true
enableRobotsTXT: true
canonifyURLs: true

outputs:
  home: ["HTML", "RSS", "JSON"]
  section: ["HTML", "RSS"]

markup:
  goldmark:
    renderer:
      unsafe: true
  highlight:
    style: dracula

params:
  search: true
  description: "전북대학교 컴퓨터인공지능학부 성윤오 포트폴리오"
  author: "성윤오"

canonifyURLs: true
relativeURLs: false