title: "성윤오 포트폴리오"
baseURL: "https://s44158619-code.github.io/"

defaultContentLanguage: ko

hasCJKLanguage: true

languages:
  ko:
    languageCode: ko-KR
    contentDir: content/ko
    title: "성윤오 포트폴리오"
    weight: 1
  en:
    languageCode: en-US
    contentDir: content/en
    title: "Seong Yunoh's Portfolio"
    weight: 2

# -------------------------------------------------
# Hugo 고급 설정
# -------------------------------------------------
enableGitInfo: false
summaryLength: 30
paginate: 10
enableEmoji: true
enableRobotsTXT: true
outputs:
  home: [HTML, RSS, JSON, WebAppManifest]
  section: [HTML, RSS]
markup:
  goldmark:
    renderer:
      unsafe: true
  highlight:
    style: dracula
