security:
  funcs:
    getenv: ["^HUGO_", "^CI$", "WC_POST_CSS"]

title: "Yoon Oh"
baseURL: "https://s44158619-code.github.io/"

defaultContentLanguage: ko
hasCJKLanguage: true

languages:
  ko:
    languageCode: ko-KR
    title: "You know Yoon Oh"
    weight: 1
  # en:
  #   languageCode: en-US
  #   title: "Seong Yoonoh's Portfolio"
  #   weight: 2

enableGitInfo: false
summaryLength: 30
paginate: 10
enableEmoji: true
enableRobotsTXT: true
canonifyURLs: true

outputs:
  home: ["HTML", "RSS", "JSON"]
  section: ["HTML", "RSS"]

markup:
  goldmark:
    renderer:
      unsafe: true
  highlight:
    style: dracula

params:
  search: true
  description: "전북대학교 컴퓨터인공지능학부 성윤오 포트폴리오"
  author: "성윤오"
