# Languages
#   Create a section for each of your site's languages.
#   Documentation: https://docs.hugoblox.com/reference/language/

# Default language
ko:
  languageCode: ko
  contentDir: content/ko
  title: Yoon Oh
  languageName: "한국어"
  weight: 1

en:
  languageCode: en
  contentDir: content/en
  title: Yoon Oh
  languageName: "English"
  weight: 2
