main:
  - name: "Home"
    url: "/"
    weight: 1
  - name: "About"
    url: "/about/"
    weight: 2
  - name: "Projects"
    url: "/project/"
    weight: 3
    identifier: "projects"
  - name: "Contact"
    url: "/contact/"
    weight: 4
  - name: "Resources"
    url: "/resources/"
    weight: 5
    identifier: "resources"
  - parent: "projects"
    name: "Tech Projects"
    url: "/tags/tech-projects/"
    weight: 31
  - parent: "projects"
    name: "Writings"
    url: "/tags/writings/"
    weight: 32
  - parent: "projects"
    name: "Reviews"
    url: "/tags/reviews/"
    weight: 33
  - parent: "resources"
    name: "Download Resume"
    url: "/files/resume.pdf"
    weight: 51
  - parent: "resources"
    name: "GitHub"
    url: "https://github.com/s44158619-code"
    weight: 52
