appearance:
  theme_day: custom
  theme_night: custom
  font: minimal
  font_size: L

# SEO
marketing:
  seo:
    site_type: Person
    local_business_type: "University Student"
    org_name: "전북대학교"
    site_title: "전북대 성윤오 포트폴리오"
    description: "전북대학교 컴퓨터인공지능학부 학생 성윤오의 포트폴리오 사이트입니다. 프로젝트, 기술, 관심 분야를 소개합니다."
    keywords:
      ["전북대", "성윤오", "포트폴리오", "컴퓨터인공지능학부", "AI", "Projects"]
    twitter: ""
    image: "icon.png"
    google_analytics: ""
    baidu_tongji: ""
    google_tag_manager: ""
    microsoft_clarity: ""
  verification:
    google: "Izntv3d_scj_G8AIcXk-C7GL_sR0d3-ODgDyhxiZuOc"
    baidu: ""

header:
  navbar:
    enable: true
    align: r
    show_logo: true
    show_language: true
    show_day_night: true
    show_search: true
    highlight_active_link: false

branding:
  logo:
    light: "media/logo-light.png"
    dark: "media/logo-dark.png"
  logo_width: 180

footer:
  copyright:
    notice: "© {year} 성윤오 (Yoonoh Seong). This work is licensed under {license}"
    license:
      enable: true
      allow_derivatives: false
      share_alike: true
      allow_commercial: false

locale:
  date_format: "Jan 2, 2006"
  time_format: "3:04 PM"

features:
  syntax_highlighter:
    enable: true
    extra_languages:
      - r
      - latex
  math:
    enable: false
  privacy_pack:
    enable: false
  repository:
    url: "https://github.com/s44158619-code/s44158619-code.github.io"
    content_dir: content
    branch: main
  avatar:
    gravatar: false
    shape: circle
  comment:
    provider: ""
    disqus:
      shortname: ""
      show_count: true
    commento:
      url: ""
    giscus:
      repo: ""
      repo_id: ""
      category: ""
      category_id: ""
  search:
    provider: wowchemy
    algolia:
      app_id: ""
      api_key: ""
      index_name: ""
      show_logo: false
  map:
    provider: "maplink"
    api_key: ""
    zoom: 16

extensions:
  cms:
    branch: main
    local_backend: false
  academicons:
    enable: false
  fontawesome:
    enable: true

images:
  - "/media/icon.png"

social:
  - icon: github
    icon_pack: fab
    link: "https://github.com/s44158619-code"
  - icon: linkedin
    icon_pack: fab
    link: "https://linkedin.com/in/윤오-성-a4b90b388"
  - icon: facebook
    icon_pack: fab
    link: "https://facebook.com/seong.yun.o.360316"
  - icon: youtube
    icon_pack: fab
    link: "https://youtube.com/@성윤오-o2j"
  - icon: instagram
    icon_pack: fab
    link: "https://instagram.com/syo_lll0"
  - icon: blog
    icon_pack: fas
    link: "https://blog.naver.com/csaicsai"
